cmake_minimum_required(VERSION 3.22)
project(TranslationTests LANGUAGES CXX)
add_executable(TranslationTests TranslationTests.cpp)
target_compile_features(TranslationTests PRIVATE cxx_std_23)
target_include_directories(TranslationTests PRIVATE ../../include)
enable_testing()
add_test(NAME TranslationTests COMMAND TranslationTests)

option(TEST_JSON_TRANSLATOR "Also test the optional JSON translator" OFF)
if(TEST_JSON_TRANSLATOR)
    find_package(RapidJSON CONFIG REQUIRED)
    add_executable(JSONTranslationTests TranslationTests.cpp)
    target_compile_features(JSONTranslationTests PRIVATE cxx_std_23)
    target_compile_definitions(JSONTranslationTests PRIVATE TEST_JSON_TRANSLATOR)
    target_include_directories(JSONTranslationTests PRIVATE ../../include)
    target_link_libraries(JSONTranslationTests PRIVATE rapidjson)
    add_test(NAME JSONTranslationTests COMMAND JSONTranslationTests)
endif()
